# Generated by Django 4.0.2 on 2022-05-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='phone',
            field=models.CharField(default='000000000', max_length=15),
            preserve_default=False,
        ),
    ]
