# Generated by Django 4.0.2 on 2022-03-01 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='automation.email'),
        ),
    ]
