# Generated by Django 3.2.9 on 2022-03-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_subscriber_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='Subscription_type',
            new_name='subscription',
        ),
    ]
